/*****************************************************************************************************
*This file is a part of TM2 project which goal is to create a musical instrument.*
******************************************************************************************************/
/**
 * @file main.c
 * @author Pawelec, Skomial
 * @date Jan 2021
 * @brief File containing the main function.
 * @ver 0.1
 */


#include "pit.h"



 int main (void) { 
	 Init_DAC(); // Initialise DAC
	 init_array(); // Initialise arrays in dat_prep file
	 Ps2_comm_init(); // Initalise receive from PS/2 keyboard
	 
	 // #TODO: configure PIT to generate interrupts at the same rate as sample rate.
	 // /\ These interrupts should have smaller priority level than interrupts generated by PORTB
	 
	 
	 PIT_init();
	 while(1)
	 {
		 if(chck_if_dat_rdy())
		 {
			decode_keys();
		 }
	 }
 }

