/*****************************************************************************************************
*This file is a part of TM2 project which goal is to create a musical instrument.*
******************************************************************************************************/
/**
 * @file main.c
 * @author Pawelec, Skomial
 * @date Dec 2020
 * @brief File containing the main function.
 * @ver 0.1
 */


#include "dsp.h"



 int main (void) { 
	 uint8_t* tune_idx;
	 Init_DAC(); // Initialise DAC
	 init_array(); // Initialise arrays in dat_prep file
	 Ps2_comm_init(); // Initalise receive from PS/2 keyboard
	 // #TODO: configure PIT to generate interrupts at the same rate as sample rate.
	 // /\ These interrupts should have smaller priority level than interrupts generated by PORTB
	 while(1)
	 {
		 if(chck_if_dat_rdy())
		 {
			 tune_idx = decode_keys(); // Get pointer to array with tones indices
			
		 }
	 }
	 
	 
	 
 }

